[package]
name = "smcurser"
version = "0.1.0"
authors = ["Ian Welker <iandwelker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
crossterm = "0.18"
tui = { version = "0.14", default-features = false, features = ['crossterm'] }
ureq = { version = "2.0.1", features = ["json", "tls"] }
rustls = { version = "0.19.0", features = ["dangerous_configuration"] }
webpki = "*"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0"
textwrap = "0.13.2"
unicode-segmentation = "1.7.1"
chrono = "0.4.19"
multipart = "0.17.1"
mime_guess = "2.0.3"
tungstenite = { version = "0.12.0", features = ["tls"] }
url = "2.2.0"
