[package]
name = "smcurser"
version = "0.1.0"
authors = ["Ian Welker <iandwelker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
crossterm = "0.18"
tui = { version = "0.14", default-features = false, features = ['crossterm', 'serde'] }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11.0", features = ["native-tls", "blocking", "gzip", "multipart"] }
native-tls = "0.2.7"
textwrap = "0.13.2"
unicode-segmentation = "1.7.1"
chrono = "0.4.19"
tungstenite = { version = "0.12.0", features = ["tls"] }
url = "2.2.0"
open = "1.4.0"
toml = "0.5.8"
dirs = "3.0.1"
