[ugly]
selected_box = [254, 0, 0]
unselected_box = [0, 254, 0]
my_underline = [0, 0, 254]
their_underline = [254, 0, 0]
selected_underline = [0, 254, 0]
chat_indicator = [0, 0, 254]
unread_indicator = [254, 0, 0]
text_color = [0, 254, 0]
hints_box = [0, 0, 254]
